Homework 1
================
Emma Warshaw
2022-09-23

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

# Problem 1

This problem will focus on use of inline R code, plotting and the
behavior of `ggplot` for variables of different types.

I will first download the data package `penguins` with a command
directly in the console per the assignment instructions.

Now, I’ll load the dataset in the following code:

``` r
data("penguins", package = "palmerpenguins")
penguins
```

    ## # A tibble: 344 × 8
    ##    species island    bill_length_mm bill_depth_mm flipper_…¹ body_…² sex    year
    ##    <fct>   <fct>              <dbl>         <dbl>      <int>   <int> <fct> <int>
    ##  1 Adelie  Torgersen           39.1          18.7        181    3750 male   2007
    ##  2 Adelie  Torgersen           39.5          17.4        186    3800 fema…  2007
    ##  3 Adelie  Torgersen           40.3          18          195    3250 fema…  2007
    ##  4 Adelie  Torgersen           NA            NA           NA      NA <NA>   2007
    ##  5 Adelie  Torgersen           36.7          19.3        193    3450 fema…  2007
    ##  6 Adelie  Torgersen           39.3          20.6        190    3650 male   2007
    ##  7 Adelie  Torgersen           38.9          17.8        181    3625 fema…  2007
    ##  8 Adelie  Torgersen           39.2          19.6        195    4675 male   2007
    ##  9 Adelie  Torgersen           34.1          18.1        193    3475 <NA>   2007
    ## 10 Adelie  Torgersen           42            20.2        190    4250 <NA>   2007
    ## # … with 334 more rows, and abbreviated variable names ¹​flipper_length_mm,
    ## #   ²​body_mass_g

Let’s calculate the mean flipper length for use in the discussion of the
data set:

``` r
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

Short description of the dataset: The ‘penguins’ dataset has `nrow=344`
and `ncol=8`. There are a total of eight variables including: species,
island where the penguin lives, bill length (millimeters), bill depth
(millimeters), flipper length (millimeters), body mass (grams), sex and
year. The average flipper length for penguins in the dataset is 200.92
millimeters.

Now make a scatterplot of `flipper_length_mm` (y) vs `bill_length_mm`
(x). Color the points using the `species` variable (adding `color=...`)
inside the `aes` in your `ggplot` code. Then, export the scatterplot to
the project directory using `ggsave`.

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point() 
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_ew2718_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

``` r
ggsave("scatterplot_problem_1.pdf")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values (geom_point).

# Problem 2

This problem is intended to emphasize variable types and introduce
coercion; some awareness of how R treats numeric, character, and factor
variables is necessary for working with these data types in practice.

Create a data frame comprised of: - a random sample of size 10 from a
standard Normal distribution - a logical vector indicating whether
elements of the sample are greater than 0 - a character vector of length
10 - a factor vector of length 10, with 3 different factor “levels”

``` r
problem2_df = tibble(
  normal_var = rnorm(10),
  logical_var = normal_var > 0,
  character_var = character(length = 10),
  factor_var = factor(character(length = 10),(levels = 3))
)
```

Try to take the mean of each variable in the data frame. What works and
what doesn’t?

For the normal variable:

``` r
pull(problem2_df, var = normal_var)
```

    ##  [1] -0.2229025 -0.8001727  1.4779900 -1.4430061 -0.3420675  0.2922253
    ##  [7]  2.7612181  0.3169566 -0.7529985 -1.2719054

``` r
mean(problem2_df$normal_var)
```

    ## [1] 0.001533728

This works.

For the logical variable:

``` r
pull(problem2_df, var = logical_var)
```

    ##  [1] FALSE FALSE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE

``` r
mean(problem2_df$logical_var)
```

    ## [1] 0.4

This also works.

For the character variable:

``` r
pull(problem2_df, var = character_var)
```

    ##  [1] "" "" "" "" "" "" "" "" "" ""

``` r
mean(problem2_df$character_var)
```

    ## Warning in mean.default(problem2_df$character_var): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

This does not work because the argument is not numeric or logical.

For the factor variable:

``` r
pull(problem2_df, var = factor_var)
```

    ##  [1] <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA>
    ## Levels: 3

``` r
mean(problem2_df$factor_var)
```

    ## Warning in mean.default(problem2_df$factor_var): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

This also does not work because the argument is not numeric or logical.

Write a code chunk that applies `as.numeric` to the logical, factor, and
character variables.

``` r
as.numeric(problem2_df$logical_var)
as.numeric(problem2_df$factor_var)
as.numeric(problem2_df$character_var)
```

This code turns the logical variable into binary coding, correspdoing to
whether or not the logical statement was met. It gives ‘NA’ for the
factor and character variables. This is because we’re asking r to assign
numeric values to a character string variable. It doesn’t know what to
assign as the numeric variable, so it gives NA. This also explains why
you cannot take a mean for either of these variables. Since they’re
character based and not numeric, it can’t calculate anything.
